(define (coin-change x)
  (define (denom coin)
    (cond ((= coin 1) 1)
          ((= coin 2) 5)
          ((= coin 3) 10)
          ((= coin 4) 25)
          ((= coin 5) 50)
          (else 0)))
  (define (cc amount coin)
    (cond ((or (= coin 0) (< amount 0)) 0)
          ((= amount 0) 1)
          (else (+ (cc amount (- coin 1))
                   (cc (- amount (denom coin)) coin)))))
  (cc x 5))
